title: Open Song Database
email: osdbapi@gmail.com
description: >- # this means to ignore newlines until "baseurl:". Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Welcome to the Open Song Database APi
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://osdbapi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cokoghenun
github_username:  cokoghenun

# Build settings
theme: jekyll-theme-leap-day
github:
  repository_name: Open Song Database
  project_tagline: Welcome to the Open Song Database API
  repository_url: https://github.com/cokoghenun/open-song-database
  owner_url: https://github.com/cokoghenun
  owner_name: cokoghenun
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dist/
  - src/
  - nodemon.json
  - package.json
  - yarn.lock